### ISSUE TITLE
ClientSideEvents just js declaration ?

### ISSUE THREAD

**Issue by masherak** [HajbokRobert/FullCalendarMVC#3]
Please, is there some option how declare this - (html helper) ClientSideEvents -> EventResize(string) and EventDrop(string) in natively csharp for example POST/PUT Url action which will call if event fired ? I see just js declaration callback in string. Thank you very much

**Comment by RobertHajbok** [comment]
EventResize and EventDrop both accept a function as parameter in the native API, that's why you can pass just a JS function as string. I guess you can do something like this if you really want:
```
@{
    string eventResize = $"function() {{ console.log('event resize'); var x = {Url.Action("EventResize", "Home")} }}";
}

@Html.FullCalendar(settings =>
{
     ...
     settings.ClientSideEvents.EventResize = eventResize;
}
```
 See their documentation: https://fullcalendar.io/docs/eventResize

**Comment by masherak** [comment]
Thank you for your answer ! Have a nice day
