### ISSUE TITLE
CalendarView

### ISSUE THREAD

**Issue by LordNashor** [HajbokRobert/FullCalendarMVC#4]
About the exemple code provided

```
@Html.FullCalendar(settings =>
{
    settings.Name = "calendar";
    settings.CssClass = "css-test";
    settings.Header = new Header
    {
        Left = new ControlsBuilder().AddButton(HeaderButton.Prev).AddSeparator(HeaderSeparator.Adjacent)
                    .AddButton(HeaderButton.Next).AddSeparator(HeaderSeparator.Gap).AddButton(HeaderButton.Today),
        Center = new ControlsBuilder().AddTitle(),
        Right = new ControlsBuilder("month,agendaWeek ").AddView(CalendarView.AgendaDay)
    };
    settings.DefaultView = CalendarView.AgendaDay;
    settings.Editable = true;
    settings.AllDaySlot = false;
    settings.Selectable = true;
    settings.SlotDuration = TimeSpan.FromMinutes(15);
    settings.Events = Events.AsJsonFeed(Url.Action("GetDiaryEvents", "Home"));
})
```

What does `CalendarView` stands for?

**Comment by RobertHajbok** [comment]
It's the views type on this page https://fullcalendar.io/docs. Documentation used to be cleaner though...

**Comment by LordNashor** [comment]
I couldn't find this enum `CalendarView` anywhere to make the reference. Turns out that I found an enum called `AvailableView` that worked exactly as `CalendarView` should. Isn't it an error in the given exemple? Shouldn't `CalendarView` be `AvailableView`?

**Comment by RobertHajbok** [comment]
You are right, ```CalendarView``` was renamed to ```AvailableView``` in [this](https://github.com/HajbokRobert/FullCalendarMVC/commit/341a4b3fb5bc06095bfc0de65c806b90c5f8f34d) commit. I will update the readme, thanks for letting me know!
