### ISSUE TITLE
Adding eventRender to settings

### ISSUE THREAD

**Issue by richardboman** [HajbokRobert/FullCalendarMVC#5]
Is there any way to add eventRender in order to display a tooltip for events?

**Comment by RobertHajbok** [comment]
How about something like this? This is using qTip but you can use any other library.
```cshtml
@Html.FullCalendar(settings =>
{
    ...
    settings.ClientSideEvents.EventRender = @"function(event, element) {
        element.qtip({
            content: event.description
        });
    }";
}
```

You can see an example of it [here](https://github.com/HajbokRobert/FullCalendarMVC/blob/master/FullCalendarMVC/FullCalendar.UI/Views/Home/_FullCalendar.cshtml)
